version: "3"
services:
  payment-platform-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    image: ppa
    container_name: ppa
    restart: unless-stopped
    env_file: .env
    depends_on:
        - redis
  ppa-redis:
    image: redis
    container_name: ppa-redis
    ports:
      - "6379:6379"