export const quotesConstants = [
  'qs_quote_handleQuoteRequest',
  'qs_quote_forwardQuoteRequest',
  'qs_quote_forwardQuoteRequestResend',
  'qs_quote_handleQuoteUpdate',
  'qs_quote_forwardQuoteUpdate',
  'qs_quote_forwardQuoteUpdateResend',
  'qs_quote_handleQuoteError',
  'qs_quote_forwardQuoteGet',
  'qs_quote_sendErrorCallback',

  'qs_bulkquote_forwardBulkQuoteRequest',
  'qs_quote_forwardBulkQuoteUpdate',
  'qs_quote_forwardBulkQuoteGet',
  'qs_quote_forwardBulkQuoteError',
  'qs_bulkQuote_sendErrorCallback',

  'QuotesErrorByIDPut',
  'QuotesByIdGet',
  'QuotesByIdPut',
  'QuotesPost',
  'BulkQuotesErrorByIdPut',
  'BulkQuotesByIdGet',
  'BulkQuotesByIdPut',
  'BulkQuotesPost',
];
